services:
  backend:
    build: .
    ports:
      - 8080:8080
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD = teste
    volumes:
      - dbdata:/var/lib/mysql