services:
  backend:
    build: .
    ports:
      - "80:80"
    networks:
      - nunesNetwork
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: nunes
      MARIADB_ROOT_PASSWORD: root
    volumes:
      # Copia os scripts SQL da pasta DB para ser inicializados com o container do MariaDB
      - ./db:/docker-entrypoint-initdb.d:z
      - dbdata:/var/lib/mysql
    expose:
      - 3306
    networks:
      - nunesNetwork
volumes:
  dbdata: {}
networks:
  nunesNetwork:
