server:
    port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization : true
  mustache:
    check-template-location: false
vaadin:
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

