server:
    port: 80
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/nunes
    username: root
    password: 
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization : true
  mustache:
    check-template-location: false
vaadin:
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

